# Generated by Django 4.2.7 on 2023-11-12 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0002_sessionaccount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Posting",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=50)),
                ("condition", models.EmailField(max_length=50)),
                ("price", models.FloatField()),
                ("description", models.CharField(max_length=1000)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.account"
                    ),
                ),
            ],
        ),
    ]
