# Generated by Django 4.1.13 on 2023-11-12 03:24

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Posting",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=50)),
                ("condition", models.EmailField(max_length=50)),
                ("price", models.FloatField()),
                ("description", models.CharField(max_length=1000)),
                ("residential_hall", models.CharField(max_length=50)),
                (
                    "categories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10), blank=True, size=8
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.account"
                    ),
                ),
            ],
        ),
    ]
