services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypass
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: