# Generated by Django 4.1.13 on 2023-11-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("posting_id", models.IntegerField()),
                ("image_data", models.FileField(upload_to="")),
            ],
        ),
    ]
