# Generated by Django 4.1.13 on 2023-11-12 05:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("image", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Image",
        ),
    ]
