# Generated by Django 4.2.7 on 2023-11-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.EmailField(max_length=50, unique=True)),
                ("picture_url", models.URLField()),
            ],
        ),
    ]
