# Generated by Django 4.1.13 on 2023-11-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionaccount",
            name="session_token",
            field=models.CharField(max_length=1000),
        ),
    ]
