# Generated by Django 4.1.13 on 2023-11-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_sessionaccount_session_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sessionaccount",
            name="session_token",
            field=models.CharField(max_length=2000),
        ),
    ]
